# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
