# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20171126_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_title',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='album.Album'),
            preserve_default=False,
        ),
    ]
