# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20171126_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
