# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20171126_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='filter_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
