# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_photo_filter_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered_photo_url', models.CharField(max_length=100)),
                ('primary_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Photo')),
            ],
        ),
    ]
