# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_filteredphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='filter_photo',
        ),
    ]
