# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_auto_20171204_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredphoto',
            name='filtered_photo_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
