# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_auto_20171204_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='main_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
