# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:18
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_auto_20171204_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='main_photo',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='filteredphoto',
            name='filtered_photo_url',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
    ]
